# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 94b0f90c27a64ba19c5f80e731e56f61c303d2fd7236b9f28755ae0740955272c5ca8b0a57b04ba0692e322e311b2c2df5fd1ee4436265327bdca63d9e4b6b6e

test:
  secret_key_base: 39674db69245396e1868d74a9f4e77dbe00daa9d69f13e8ae8b241dded8bce38f670a770458f909a955a9586c1a1ab156481dd46ad8080e1c5061837cb121df8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
