CategoriaQueixa.create!([
  {nome: "Olhos"},
  {nome: "Nariz"},
  {nome: "Membros Superiores"},
  {nome: "Membros Inferiores"}
])
Cidade.create!([
  {nome: "GURUPI", uf: "TO", latitude: "-11,72", longitude: "-49,06", pacientes_count: -1},
  {nome: "NOVA OLINDA", uf: "TO", latitude: "-7,63", longitude: "-48,42", pacientes_count: 1},
  {nome: "MURICILANDIA", uf: "TO", latitude: "-7,14", longitude: "-48,61", pacientes_count: 0},
  {nome: "PALMEIRAS DO TOCANTINS", uf: "TO", latitude: nil, longitude: nil, pacientes_count: 0},
  {nome: "PAU D'ARCO", uf: "TO", latitude: nil, longitude: nil, pacientes_count: 0},
  {nome: "ABREULANDIA", uf: "TO", latitude: "-9,62", longitude: "-49,15", pacientes_count: 0},
  {nome: "AGUIARNOPOLIS", uf: "TO", latitude: "-6,56", longitude: "-47,46", pacientes_count: 0},
  {nome: "ALIANCA DO TOCANTINS", uf: "TO", latitude: "-11,3", longitude: "-48,93", pacientes_count: 0},
  {nome: "ALMAS", uf: "TO", latitude: "-11,57", longitude: "-47,17", pacientes_count: 0},
  {nome: "ALVORADA", uf: "TO", latitude: "-12,48", longitude: "-49,12", pacientes_count: 0},
  {nome: "ANANAS", uf: "TO", latitude: "-6,36", longitude: "-48,07", pacientes_count: 0},
  {nome: "APARECIDA DO RIO NEGRO", uf: "TO", latitude: "-9,95", longitude: "-47,97", pacientes_count: 0},
  {nome: "ARAGOMINAS", uf: "TO", latitude: "-7,16", longitude: "-48,52", pacientes_count: 0},
  {nome: "ARAGUACEMA", uf: "TO", latitude: "-8,8", longitude: "-49,55", pacientes_count: 0},
  {nome: "ARAGUACU", uf: "TO", latitude: "-12,93", longitude: "-49,82", pacientes_count: 0},
  {nome: "ARAGUAINA", uf: "TO", latitude: "-7,19", longitude: "-48,2", pacientes_count: 0},
  {nome: "ARAGUATINS", uf: "TO", latitude: "-5,65", longitude: "-48,12", pacientes_count: 0},
  {nome: "ARAPOEMA", uf: "TO", latitude: "-7,65", longitude: "-49,06", pacientes_count: 0},
  {nome: "ARRAIAS", uf: "TO", latitude: "-12,93", longitude: "-46,93", pacientes_count: 0},
  {nome: "AUGUSTINOPOLIS", uf: "TO", latitude: "-5,46", longitude: "-47,88", pacientes_count: 0},
  {nome: "AURORA DO TOCANTINS", uf: "TO", latitude: "-12,71", longitude: "-46,4", pacientes_count: 0},
  {nome: "AXIXA DO TOCANTINS", uf: "TO", latitude: "-5,61", longitude: "-47,76", pacientes_count: 0},
  {nome: "BABACULANDIA", uf: "TO", latitude: "-7,2", longitude: "-47,75", pacientes_count: 0},
  {nome: "BARRA DO OURO", uf: "TO", latitude: "-7,68", longitude: "-47,68", pacientes_count: 0},
  {nome: "BARROLANDIA", uf: "TO", latitude: "-9,83", longitude: "-48,72", pacientes_count: 0},
  {nome: "BERNARDO SAYAO", uf: "TO", latitude: "-7,87", longitude: "-48,88", pacientes_count: 0},
  {nome: "BOM JESUS DO TOCANTINS", uf: "TO", latitude: "-8,96", longitude: "-48,16", pacientes_count: 0},
  {nome: "BRASILANDIA DO TOCANTINS", uf: "TO", latitude: "-8,38", longitude: "-48,48", pacientes_count: 0},
  {nome: "BREJINHO DE NAZARE", uf: "TO", latitude: "-11", longitude: "-48,56", pacientes_count: 0},
  {nome: "BURITI DO TOCANTINS", uf: "TO", latitude: "-5,31", longitude: "-48,22", pacientes_count: 0},
  {nome: "CACHOEIRINHA", uf: "TO", latitude: "-6,12", longitude: "-47,92", pacientes_count: 0},
  {nome: "CARIRI DO TOCANTINS", uf: "TO", latitude: "-11,89", longitude: "-49,16", pacientes_count: 0},
  {nome: "CARMOLANDIA", uf: "TO", latitude: "-7,03", longitude: "-48,39", pacientes_count: 0},
  {nome: "CARRASCO BONITO", uf: "TO", latitude: "-5,32", longitude: "-48,03", pacientes_count: 0},
  {nome: "CASEARA", uf: "TO", latitude: "-9,27", longitude: "-49,95", pacientes_count: 0},
  {nome: "CENTENARIO", uf: "TO", latitude: "-8,95", longitude: "-47,33", pacientes_count: 0},
  {nome: "CHAPADA DA NATIVIDADE", uf: "TO", latitude: "-11,61", longitude: "-47,75", pacientes_count: 0},
  {nome: "COLINAS DO TOCANTINS", uf: "TO", latitude: "-8,05", longitude: "-48,47", pacientes_count: 0},
  {nome: "COLMEIA", uf: "TO", latitude: "-8,72", longitude: "-48,76", pacientes_count: 0},
  {nome: "COMBINADO", uf: "TO", latitude: "-12,79", longitude: "-46,53", pacientes_count: 0},
  {nome: "CONCEICAO DO TOCANTINS", uf: "TO", latitude: "-12,21", longitude: "-47,29", pacientes_count: 0},
  {nome: "COUTO DE MAGALHAES", uf: "TO", latitude: "-8,28", longitude: "-49,24", pacientes_count: 0},
  {nome: "CRISTALANDIA", uf: "TO", latitude: "-10,6", longitude: "-49,19", pacientes_count: 0},
  {nome: "CRIXAS DO TOCANTINS", uf: "TO", latitude: "-11,1", longitude: "-48,91", pacientes_count: 0},
  {nome: "DARCINOPOLIS", uf: "TO", latitude: "-6,71", longitude: "-47,76", pacientes_count: 0},
  {nome: "DIVINOPOLIS DO TOCANTINS", uf: "TO", latitude: "-9,8", longitude: "-49,21", pacientes_count: 0},
  {nome: "DOIS IRMAOS DO TOCANTINS", uf: "TO", latitude: "-9,25", longitude: "-49,06", pacientes_count: 0},
  {nome: "DUERE", uf: "TO", latitude: "-11,34", longitude: "-49,27", pacientes_count: 0},
  {nome: "ESPERANTINA", uf: "TO", latitude: "-5,34", longitude: "-48,51", pacientes_count: 0},
  {nome: "FATIMA", uf: "TO", latitude: "-10,76", longitude: "-48,9", pacientes_count: 0},
  {nome: "FIGUEIROPOLIS", uf: "TO", latitude: "-12,13", longitude: "-49,17", pacientes_count: 0},
  {nome: "FORMOSO DO ARAGUAIA", uf: "TO", latitude: "-11,79", longitude: "-49,52", pacientes_count: 0},
  {nome: "FORTALEZA DO TABOCAO", uf: "TO", latitude: "-9,05", longitude: "-48,51", pacientes_count: 0},
  {nome: "GOIANORTE", uf: "TO", latitude: "-8,77", longitude: "-48,93", pacientes_count: 0},
  {nome: "GOIATINS", uf: "TO", latitude: "-7,71", longitude: "-47,31", pacientes_count: 0},
  {nome: "GUARAI", uf: "TO", latitude: "-8,83", longitude: "-48,51", pacientes_count: 0},
  {nome: "IPUEIRAS", uf: "TO", latitude: "-11,23", longitude: "-48,46", pacientes_count: 0},
  {nome: "ITACAJA", uf: "TO", latitude: "-8,39", longitude: "-47,76", pacientes_count: 0},
  {nome: "ITAPIRATINS", uf: "TO", latitude: "-8,38", longitude: "-48,11", pacientes_count: 0},
  {nome: "ITAPORA DO TOCANTINS", uf: "TO", latitude: "-8,57", longitude: "-48,68", pacientes_count: 0},
  {nome: "JAU DO TOCANTINS", uf: "TO", latitude: "-12,65", longitude: "-48,59", pacientes_count: 0},
  {nome: "JUARINA", uf: "TO", latitude: "-8,11", longitude: "-49,06", pacientes_count: 0},
  {nome: "LAGOA DA CONFUSAO", uf: "TO", latitude: "-10,79", longitude: "-49,62", pacientes_count: 0},
  {nome: "LAGOA DO TOCANTINS", uf: "TO", latitude: "-10,37", longitude: "-47,55", pacientes_count: 0},
  {nome: "LAJEADO", uf: "TO", latitude: "-9,75", longitude: "-48,35", pacientes_count: 0},
  {nome: "LIZARDA", uf: "TO", latitude: "-9,59", longitude: "-46,67", pacientes_count: 0},
  {nome: "LUZINOPOLIS", uf: "TO", latitude: "-6,18", longitude: "-47,85", pacientes_count: 0},
  {nome: "MARIANOPOLIS DO TOCANTINS", uf: "TO", latitude: "-9,79", longitude: "-49,65", pacientes_count: 0},
  {nome: "MATEIROS", uf: "TO", latitude: "-10,54", longitude: "-46,42", pacientes_count: 0},
  {nome: "MAURILANDIA DO TOCANTINS", uf: "TO", latitude: "-5,95", longitude: "-47,5", pacientes_count: 0},
  {nome: "MIRACEMA DO TOCANTINS", uf: "TO", latitude: "-9,56", longitude: "-48,39", pacientes_count: 0},
  {nome: "MONTE DO CARMO", uf: "TO", latitude: "-10,76", longitude: "-48,1", pacientes_count: 0},
  {nome: "MONTE SANTO DO TOCANTINS", uf: "TO", latitude: "-10", longitude: "-48,99", pacientes_count: 0},
  {nome: "NOVA ROSALANDIA", uf: "TO", latitude: "-10,56", longitude: "-48,91", pacientes_count: 0},
  {nome: "NOVO ACORDO", uf: "TO", latitude: "-9,96", longitude: "-47,67", pacientes_count: 0},
  {nome: "NOVO ALEGRE", uf: "TO", latitude: "-12,93", longitude: "-46,57", pacientes_count: 0},
  {nome: "NOVO JARDIM", uf: "TO", latitude: "-11,82", longitude: "-46,62", pacientes_count: 0},
  {nome: "PALMEIRANTE", uf: "TO", latitude: "-7,86", longitude: "-47,92", pacientes_count: 0},
  {nome: "PALMEIROPOLIS", uf: "TO", latitude: "-13,04", longitude: "-48,4", pacientes_count: 0},
  {nome: "PARAISO DO TOCANTINS", uf: "TO", latitude: "-10,17", longitude: "-48,86", pacientes_count: 0},
  {nome: "PARANA", uf: "TO", latitude: "-12,61", longitude: "-47,88", pacientes_count: 0},
  {nome: "NAZARE", uf: "TO", latitude: "-6,37", longitude: "-47,66", pacientes_count: 1},
  {nome: "PORTO NACIONAL", uf: "TO", latitude: "-10,7", longitude: "-48,41", pacientes_count: 0},
  {nome: "PRAIA NORTE", uf: "TO", latitude: "-5,39", longitude: "-47,81", pacientes_count: 0},
  {nome: "PRESIDENTE KENNEDY", uf: "TO", latitude: "-8,53", longitude: "-48,5", pacientes_count: 0},
  {nome: "PUGMIL", uf: "TO", latitude: "-10,42", longitude: "-48,89", pacientes_count: 0},
  {nome: "RECURSOLANDIA", uf: "TO", latitude: "-8,72", longitude: "-47,24", pacientes_count: 0},
  {nome: "RIACHINHO", uf: "TO", latitude: "-6,43", longitude: "-48,13", pacientes_count: 0},
  {nome: "RIO DA CONCEICAO", uf: "TO", latitude: "-11,4", longitude: "-46,88", pacientes_count: 0},
  {nome: "RIO DOS BOIS", uf: "TO", latitude: "-9,29", longitude: "-48,46", pacientes_count: 0},
  {nome: "RIO SONO", uf: "TO", latitude: "-9,34", longitude: "-47,9", pacientes_count: 0},
  {nome: "SAMPAIO", uf: "TO", latitude: "-5,34", longitude: "-47,87", pacientes_count: 0},
  {nome: "SANDOLANDIA", uf: "TO", latitude: "-12,53", longitude: "-49,92", pacientes_count: 0},
  {nome: "SANTA FE DO ARAGUAIA", uf: "TO", latitude: "-7,15", longitude: "-48,72", pacientes_count: 0},
  {nome: "SANTA MARIA DO TOCANTINS", uf: "TO", latitude: "-8,79", longitude: "-47,79", pacientes_count: 0},
  {nome: "SANTA RITA DO TOCANTINS", uf: "TO", latitude: "-10,86", longitude: "-48,91", pacientes_count: 0},
  {nome: "SANTA ROSA DO TOCANTINS", uf: "TO", latitude: "-11,44", longitude: "-48,12", pacientes_count: 0},
  {nome: "ANGICO", uf: "TO", latitude: "-6,39", longitude: "-47,86", pacientes_count: 0},
  {nome: "ARAGUANA", uf: "TO", latitude: "-6,58", longitude: "-48,64", pacientes_count: 0},
  {nome: "BANDEIRANTES DO TOCANTINS", uf: "TO", latitude: "-7,75", longitude: "-48,58", pacientes_count: 0},
  {nome: "CAMPOS LINDOS", uf: "TO", latitude: "-7,99", longitude: "-46,86", pacientes_count: 0},
  {nome: "CHAPADA DE AREIA", uf: "TO", latitude: "-10,14", longitude: "-49,14", pacientes_count: 0},
  {nome: "DIANOPOLIS", uf: "TO", latitude: "-11,62", longitude: "-46,82", pacientes_count: 0},
  {nome: "FILADELFIA", uf: "TO", latitude: "-7,33", longitude: "-47,49", pacientes_count: 0},
  {nome: "ITAGUATINS", uf: "TO", latitude: "-5,76", longitude: "-47,48", pacientes_count: 0},
  {nome: "LAVANDEIRA", uf: "TO", latitude: "-12,78", longitude: "-46,5", pacientes_count: 0},
  {nome: "MIRANORTE", uf: "TO", latitude: "-9,52", longitude: "-48,59", pacientes_count: 0},
  {nome: "OLIVEIRA DE FATIMA", uf: "TO", latitude: "-10,7", longitude: "-48,9", pacientes_count: 0},
  {nome: "PEDRO AFONSO", uf: "TO", latitude: "-8,96", longitude: "-48,17", pacientes_count: 0},
  {nome: "PEIXE", uf: "TO", latitude: "-12,02", longitude: "-48,53", pacientes_count: 0},
  {nome: "PEQUIZEIRO", uf: "TO", latitude: "-8,59", longitude: "-48,93", pacientes_count: 0},
  {nome: "PINDORAMA DO TOCANTINS", uf: "TO", latitude: "-11,13", longitude: "-47,57", pacientes_count: 0},
  {nome: "PIRAQUE", uf: "TO", latitude: "-6,77", longitude: "-48,29", pacientes_count: 0},
  {nome: "PIUM", uf: "TO", latitude: "-10,44", longitude: "-49,18", pacientes_count: 0},
  {nome: "PONTE ALTA DO BOM JESUS", uf: "TO", latitude: "-12,09", longitude: "-46,47", pacientes_count: 0},
  {nome: "PONTE ALTA DO TOCANTINS", uf: "TO", latitude: "-10,74", longitude: "-47,53", pacientes_count: 0},
  {nome: "PORTO ALEGRE DO TOCANTINS", uf: "TO", latitude: "-11,6", longitude: "-47,04", pacientes_count: 0},
  {nome: "SANTA TEREZA DO TOCANTINS", uf: "TO", latitude: "-10,28", longitude: "-47,8", pacientes_count: 0},
  {nome: "SANTA TEREZINHA DO TOCANTINS", uf: "TO", latitude: "-6,43", longitude: "-47,67", pacientes_count: 0},
  {nome: "SAO BENTO DO TOCANTINS", uf: "TO", latitude: "-5,91", longitude: "-48,06", pacientes_count: 0},
  {nome: "SAO FELIX DO TOCANTINS", uf: "TO", latitude: "-10,16", longitude: "-46,65", pacientes_count: 0},
  {nome: "SAO MIGUEL DO TOCANTINS", uf: "TO", latitude: "-5,55", longitude: "-47,57", pacientes_count: 0},
  {nome: "SAO SALVADOR DO TOCANTINS", uf: "TO", latitude: "-12,74", longitude: "-48,23", pacientes_count: 0},
  {nome: "SAO SEBASTIAO DO TOCANTINS", uf: "TO", latitude: "-5,25", longitude: "-48,2", pacientes_count: 0},
  {nome: "SAO VALERIO DA NATIVIDADE", uf: "TO", latitude: "-11,97", longitude: "-48,23", pacientes_count: 0},
  {nome: "SILVANOPOLIS", uf: "TO", latitude: "-11,14", longitude: "-48,16", pacientes_count: 0},
  {nome: "SITIO NOVO DO TOCANTINS", uf: "TO", latitude: "-5,6", longitude: "-47,63", pacientes_count: 0},
  {nome: "SUCUPIRA", uf: "TO", latitude: "-11,99", longitude: "-48,97", pacientes_count: 0},
  {nome: "TAGUATINGA", uf: "TO", latitude: "-12,4", longitude: "-46,43", pacientes_count: 0},
  {nome: "TAIPAS DO TOCANTINS", uf: "TO", latitude: "-12,18", longitude: "-46,98", pacientes_count: 0},
  {nome: "TALISMA", uf: "TO", latitude: "-12,79", longitude: "-49,09", pacientes_count: 0},
  {nome: "TOCANTINIA", uf: "TO", latitude: "-9,56", longitude: "-48,37", pacientes_count: 0},
  {nome: "TOCANTINOPOLIS", uf: "TO", latitude: "-6,32", longitude: "-47,41", pacientes_count: 0},
  {nome: "TUPIRAMA", uf: "TO", latitude: "-8,97", longitude: "-48,18", pacientes_count: 0},
  {nome: "TUPIRATINS", uf: "TO", latitude: "-8,39", longitude: "-48,11", pacientes_count: 0},
  {nome: "WANDERLANDIA", uf: "TO", latitude: "-6,84", longitude: "-47,96", pacientes_count: 0},
  {nome: "XAMBIOA", uf: "TO", latitude: "-6,41", longitude: "-48,53", pacientes_count: 0},
  {nome: "NATIVIDADE", uf: "TO", latitude: "-11,71", longitude: "-47,72", pacientes_count: 1},
  {nome: "PALMAS", uf: "TO", latitude: "-10,16", longitude: "-48,33", pacientes_count: 2}
])

Conduta.create!([
  {nome: "Introduzida medicação antirreacional"},
  {nome: "Introduzida PQT/PB"},
  {nome: "Introduzida PQT/MB"},
  {nome: "Iniciada investigação para resistência medicamentosa"}
])

DantQuestion.create!([
  {pergunta: 1, texto: "Número de Hipertensos cadastrados no E-SUS e/ou Município"},
  {pergunta: 2, texto: "Soma dos atendimentos aos Hipertensos nos últimos três meses pelo médico ou pelo enfermeiro na(s) UBS"},
  {pergunta: 3, texto: "Número de Óbitos de Pacientes com Hipertensão"},
  {pergunta: 4, texto: "Número de Diabéticos com Hipertensão"},
  {pergunta: 5, texto: "Soma dos atendimentos aos Diabéticos nos últimos três meses realizados por médico ou pleo enfermeiro na(s) UBS"},
  {pergunta: 6, texto: "Número de Óbitos de Pacientes com Diabetes"},
  {pergunta: 7, texto: "Número de Diabéticos com Hipertensão cadastrados "},
  {pergunta: 8, texto: "Soma dos atendimentos aos Diabéticos com Hipertensão nos últimos três meses realizados por médico ou pelo enfermeiro na UBS"},
  {pergunta: 9, texto: "Número de usuários que estão em tratamento de Hemodiálise e/ou Diálise Peritoneal relacionados com Hipertensão/Diabetes no município ou fora do domicílio, sendo acompanhados ou não pela UBS"},
  {pergunta: 10, texto: "Número de Pacientes que utilizam insulina NPH"},
  {pergunta: 11, texto: "Quantidade de frascos de insulina NPH utilizados mensalmente"},
  {pergunta: 12, texto: "Número de pacientes que utilizam insulina REGULAR"},
  {pergunta: 13, texto: "Quantidade de frascos de insulina REGULAR utilizados mensalmente"},
  {pergunta: 14, texto: "Número de Tabagista cadastrados no Município e/ou E-SUS"},
  {pergunta: 15, texto: "Número de Tabagistas atendidos nos últimos três meses"},
  {pergunta: 16, texto: "Número de Etilistas cadastrados no Município"},
  {pergunta: 17, texto: "Número de Etilistas atendidos nos últimos três meses"},
  {pergunta: 18, texto: "Número de Obesos cadastrados no Município"},
  {pergunta: 19, texto: "Grau de Obesidade I, quantos?"},
  {pergunta: 20, texto: "Grau de Obesidade II, quantos?"},
  {pergunta: 21, texto: "Grau de Obesidade III, quantos?"},
  {pergunta: 22, texto: "Somar as participações (número de vezes) em que os usuários do SUS praticaram atividades físicas nos últimos 3 meses anteriores ao mês de referência do relatório"},
  {pergunta: 23, texto: "Número de Pacientes que utilizam insulina NPH de Caneta"},
{pergunta: 24, texto: "Quantidade de frascos de insulina NPH de Caneta utilizados mensalmente"},
    {pergunta: 25, texto: "Número de pacientes que utilizam insulina REGULAR de Caneta"},
    {pergunta: 26, texto: "Quantidade de frascos de insulina REGULAR de Caneta utilizados mensalmente"}
])

Dermatologica.create!([
  {nome: "Manchas"},
  {nome: "Placas"},
  {nome: "Nódulos"},
  {nome: "Inflitrações"}
])

Diagnostico.create!([
  {nome: "Estado reacional de hanseníase"},
  {nome: "Classificação operacional inicial errônea"},
  {nome: "Recidiva de hanseníase"},
  {nome: "Recidiva e estado reacional de hanseníase"},
  {nome: "Suspeita de resistência medicamentosa"}
])

Medicamento.create!([
  {nome: "Clofazimina 50 mg"},
  {nome: "Clofazimina 100 mg"},
  {nome: "Minociclina 100 mg"},
  {nome: "Multibacilar adulto"},
  {nome: "Multibacilar infantil"},
  {nome: "Ofloxacino 400 mg"},
  {nome: "Paucibacilar Adulto"},
  {nome: "Paucibacilar Infantil"},
  {nome: "Pentoxifilina 400 mg"},
  {nome: "Prednisona 20 mg"},
  {nome: "Prednisona 5 mg"}
])
Monofilamento.create!([
  {nome: "Verde", cor: "#006600", interpretacao: "Sensibilidade \"Normal\" para mão e pé."},
  {nome: "Azul", cor: "#0066ff", interpretacao: "Sensibilidade diminuída na mão, com dificuldade quanto à discriminação fina. (dentro do \"normal\" para o pé)"},
  {nome: "Violeta", cor: "#cc33ff", interpretacao: "Sensibilidade protetora para a mão diminuída, permanecendo o suficiente para prevenir lesões. Dificuldades com a discriminação de forma e temperatura."},
  {nome: "Vermelho", cor: "#ff0000", interpretacao: "Perda da sensação protetora para a mão, e as vezes, para o pé. Vulnerável a lesões. Perda da discriminação quente/frio."},
  {nome: "Laranja", cor: "#ff6600", interpretacao: "Perda da sensação protetora para o pé, ainda podendo sentir pressão profunda e dor."},
  {nome: "Rosa", cor: "#ff1ab3", interpretacao: "Sensibilidade à pressão profunda, podendo ainda sentir dor."},
  {nome: "Preto", cor: "#000000", interpretacao: "Perda de sensibilidade à pressão profunda, normalmente podendo sentir dor."}
])

Ocupacao.create!([
  {nome: "LEGISLADORES", codigo: "1111"},
  {nome: "DIRIGENTES GERAIS DA ADMINISTRAÇÃO PÚBLICA", codigo: "1112"},
  {nome: "MINISTROS DE TRIBUNAIS", codigo: "1113"},
  {nome: "DIRIGENTES DE PRODUÇÃO E OPERAÇÕES DA ADMINISTRAÇÃO PÚBLICA", codigo: "1122"},
  {nome: "DIRIGENTES DAS ÁREAS DE APOIO DA ADMINISTRAÇÃO PÚBLICA", codigo: "1123"},
  {nome: "CHEFES DE PEQUENAS POPULAÇÕES", codigo: "1130"},
  {nome: "DIRIGENTES E ADMINISTRADORES DE ORGANIZAÇÕES DE INTERESSE PÚBLICO", codigo: "1140"},
  {nome: "DIRETORES GERAIS", codigo: "1210"},
  {nome: "DIRIGENTES DE EMPRESAS - EMPREGADORES COM MAIS DE 5 EMPREGADOS", codigo: "1219"},
  {nome: "DIRETORES DE ÁREAS DE PRODUÇÃO E OPERAÇÕES", codigo: "1220"},
  {nome: "DIRETORES DE ÁREAS DE APOIO", codigo: "1230"},
  {nome: "GERENTES DE PRODUÇÃO E OPERAÇÕES", codigo: "1310"},
  {nome: "GERENTES DE ÁREAS DE APOIO", codigo: "1320"},
  {nome: "PROFISSIONAIS DA BIOENGENHARIA, BIOTECNOLOGIA E ENGENHARIA GENÉTICA", codigo: "2011"},
  {nome: "PROFISSIONAIS DA METROLOGIA", codigo: "2012"},
  {nome: "ENGENHEIROS MECATRÔNICOS", codigo: "2021"},
  {nome: "PROFISSIONAIS DA MATEMÁTICA", codigo: "2111"},
  {nome: "PROFISSIONAIS DA ESTATÍSTICA", codigo: "2112"},
  {nome: "ESPECIALISTAS EM COMPUTAÇÃO", codigo: "2121"},
  {nome: "ENGENHEIROS EM COMPUTAÇÃO - DESENVOLVEDORES DE SOFTWARE", codigo: "2122"},
  {nome: "ESPECIALISTAS EM INFORMÁTICA", codigo: "2123"},
  {nome: "ANALISTAS DE SISTEMAS", codigo: "2124"},
  {nome: "PROGRAMADORES DE INFORMÁTICA", codigo: "2125"},
  {nome: "FÍSICOS", codigo: "2131"},
  {nome: "QUÍMICOS", codigo: "2132"},
  {nome: "PROFISSIONAIS DO ESPAÇO E DA ATMOSFERA", codigo: "2133"},
  {nome: "GEÓLOGOS E GEOFÍSICOS", codigo: "2134"},
  {nome: "ENGENHEIROS DE MATERIAIS", codigo: "2140"},
  {nome: "ARQUITETOS", codigo: "2141"},
  {nome: "ENGENHEIROS CIVIS E AFINS", codigo: "2142"},
  {nome: "ENGENHEIROS ELETROELETRÔNICOS E AFINS", codigo: "2143"},
  {nome: "ENGENHEIROS MECÂNICOS", codigo: "2144"},
  {nome: "ENGENHEIROS QUÍMICOS", codigo: "2145"},
  {nome: "ENGENHEIROS METALÚRGICOS", codigo: "2146"},
  {nome: "ENGENHEIROS DE MINAS", codigo: "2147"},
  {nome: "ENGENHEIROS AGRIMENSORES E DE CARTOGRAFIA", codigo: "2148"},
  {nome: "OUTROS ENGENHEIROS, ARQUITETOS E AFINS", codigo: "2149"},
  {nome: "OFICIAIS DE CONVÉS", codigo: "2151"},
  {nome: "OFICIAIS DE MÁQUINAS", codigo: "2152"},
  {nome: "PROFISSIONAIS DA NAVEGAÇÃO AÉREA", codigo: "2153"},
  {nome: "BIÓLOGOS E AFINS", codigo: "2211"},
  {nome: "AGRÔNOMOS E AFINS", codigo: "2221"},
  {nome: "MÉDICOS", codigo: "2231"},
  {nome: "CIRURGIÕES-DENTISTAS", codigo: "2232"},
  {nome: "VETERINÁRIOS", codigo: "2233"},
  {nome: "FARMACÊUTICOS", codigo: "2234"},
  {nome: "ENFERMEIROS DE NÍVEL SUPERIOR E AFINS", codigo: "2235"},
  {nome: "FISIOTERAPEUTAS E AFINS", codigo: "2236"},
  {nome: "NUTRICIONISTAS ", codigo: "2237"},
  {nome: "PROFESSORES DA EDUCAÇÃO INFANTIL (COM FORMAÇÃO DE NÍVEL SUPERIOR)", codigo: "2311"},
  {nome: "PROFESSORES DE DISCIPLINAS DA EDUCAÇÃO GERAL DE 1ª a 4ª SÉRIES DO ENSINO FUNDAMENTAL (COM FORMAÇÃO DE NÍVEL SUPERIOR)", codigo: "2312"},
  {nome: "PROFESSORES DE DISCIPLINAS DA EDUCAÇÃO GERAL DE 5ª A 8ª SÉRIES DO ENSINO FUNDAMENTAL", codigo: "2313"},
  {nome: "PROFESSORES DE DISCIPLINAS DA EDUCAÇÃO GERAL DO ENSINO MÉDIO", codigo: "2321"},
  {nome: "PROFESSORES E INSTRUTORES DO ENSINO PROFISSIONAL", codigo: "2330"},
  {nome: "PROFESSORES DO ENSINO SUPERIOR", codigo: "2340"},
  {nome: "PROFESSORES DE EDUCAÇÃO FÍSICA", codigo: "2391"},
  {nome: "PROFESSORES DE ALUNOS COM DEFICIÊNCIAS FÍSICAS E MENTAIS", codigo: "2392"},
  {nome: "PROGRAMADORES, AVALIADORES E ORIENTADORES DE ENSINO", codigo: "2394"},
  {nome: "ADVOGADOS", codigo: "2410"},
  {nome: "PROCURADORES DE EMPRESAS E AUTARQUIAS", codigo: "2412"},
  {nome: "OUTROS ADVOGADOS AUTÔNOMOS E DE EMPRESAS", codigo: "2419"},
  {nome: "JUÍZES E DESEMBARGADORES", codigo: "2421"},
  {nome: "PROMOTORES, DEFENSORES PÚBLICOS E AFINS", codigo: "2422"},
  {nome: "DELEGADOS DE POLÍCIA", codigo: "2423"},
  {nome: "PROFISSIONAIS EM PESQUISA E ANÁLISE ANTROPOLÓGICA E SOCIOLÓGICA", codigo: "2511"},
  {nome: "PROFISSIONAIS EM PESQUISA E ANÁLISE ECONÔMICA", codigo: "2512"},
  {nome: "PROFISSIONAIS EM PESQUISA E ANÁLISE HISTÓRICA E GEOGRÁFICA", codigo: "2513"},
  {nome: "FILÓSOFOS E CIENTISTAS POLÍTICOS", codigo: "2514"},
  {nome: "PSICÓLOGOS E PSICANALISTAS", codigo: "2515"},
  {nome: "ASSISTENTES SOCIAIS E ECONOMISTAS DOMÉSTICOS", codigo: "2516"},
  {nome: "ADMINISTRADORES", codigo: "2521"},
  {nome: "CONTADORES E AUDITORES", codigo: "2522"},
  {nome: "SECRETÁRIAS EXECUTIVAS E BILINGÜES", codigo: "2523"},
  {nome: "PROFISSIONAIS DE RECURSOS HUMANOS", codigo: "2524"},
  {nome: "PROFISSIONAIS DA ADMINISTRAÇÃO ECONÔMICO-FINANCEIRA", codigo: "2525"},
  {nome: "PROFISSIONAIS DE MARKETING, PUBLICIDADE E COMERCIALIZAÇÃO", codigo: "2531"},
  {nome: "PROFISSIONAIS DO JORNALISMO", codigo: "2611"},
  {nome: "PROFISSIONAIS DA INFORMAÇÃO", codigo: "2612"},
  {nome: "ARQUIVOLOGISTAS E MUSEÓLOGOS", codigo: "2613"},
  {nome: "FILÓLOGOS, TRADUTORES E INTÉRPRETES", codigo: "2614"},
  {nome: "ESCRITORES E REDATORES", codigo: "2615"},
  {nome: "ESPECIALISTAS EM EDITORAÇÃO", codigo: "2616"},
  {nome: "LOCUTORES E COMENTARISTAS", codigo: "2617"},
  {nome: "PRODUTORES DE ESPETÁCULOS", codigo: "2621"},
  {nome: "COREÓGRAFOS E BAILARINOS", codigo: "2622"},
  {nome: "ATORES, DIRETORES DE ESPETÁCULOS E AFINS", codigo: "2623"},
  {nome: "COMPOSITORES, MÚSICOS E CANTORES", codigo: "2624"},
  {nome: "DESENHISTAS INDUSTRIAIS (DESIGNER), ESCULTORES, PINTORES E AFINS", codigo: "2625"},
  {nome: "DECORADORES DE INTERIORES E CENÓGRAFOS", codigo: "2627"},
  {nome: "MINISTROS DE CULTOS RELIGIOSOS, MISSIONÁRIOS E AFINS", codigo: "2631"},
  {nome: "TÉCNICOS EM MECATRÔNICA", codigo: "3001"},
  {nome: "TÉCNICOS EM ELETROMECÂNICA", codigo: "3003"},
  {nome: "LABORATORISTA INDUSTRIAL", codigo: "3011"},
  {nome: "TÉCNICOS DE APOIO À BIOENGENHARIA", codigo: "3012"},
  {nome: "TÉCNICOS QUÍMICOS", codigo: "3111"},
  {nome: "TÉCNICOS PETROQUÍMICOS", codigo: "3112"},
  {nome: "TÉCNICOS EM MATERIAIS DE CERÂMICA E VIDRO", codigo: "3113"},
  {nome: "TÉCNICOS EM FABRICAÇÃO DE PRODUTOS PLÁSTICOS E DE BORRACHA", codigo: "3114"},
  {nome: "TÉCNICOS EM CONTROLE AMBIENTAL, UTILIDADES E TRATAMENTO DE EFLUENTES ", codigo: "3115"},
  {nome: "TÉCNICOS TÊXTEIS", codigo: "3116"},
  {nome: "COLORISTAS", codigo: "3117"},
  {nome: "TÉCNICOS EM CONSTRUÇÃO CIVIL - EDIFICAÇÕES", codigo: "3121"},
  {nome: "TÉCNICOS EM CONSTRUÇÃO CIVIL - OBRAS DE INFRAESTRUTURA", codigo: "3122"},
  {nome: "TÉCNICOS EM TOPOGRAFIA, AGRIMENSURA E HIDROGRAFIA", codigo: "3123"},
  {nome: "TÉCNICOS EM ELETRICIDADE E ELETROTÉCNICOS", codigo: "3131"},
  {nome: "ELETROTÉCNICOS NA MANUTENÇÃO DE MÁQUINAS E EQUIPAMENTOS", codigo: "3132"},
  {nome: "TÉCNICOS EM ELETRÔNICA", codigo: "3134"},
  {nome: "TÉCNICOS EM TELECOMUNICAÇÕES E TELEFONIA", codigo: "3135"},
  {nome: "TÉCNICOS EM CALIBRAÇÃO E INSTRUMENTAÇÃO", codigo: "3136"},
  {nome: "TÉCNICOS EM FOTÔNICA", codigo: "3137"},
  {nome: "TÉCNICOS MECÂNICOS NA FABRICAÇÃO E MONTAGEM DE MÁQUINAS, SISTEMAS E INSTRUMENTOS", codigo: "3141"},
  {nome: "TÉCNICOS MECÂNICOS (FERRAMENTAS)", codigo: "3142"},
  {nome: "TÉCNICOS EM MECÂNICA VEICULAR", codigo: "3143"},
  {nome: "TÉCNICOS MECÂNICOS NA MANUTENÇÃO DE MÁQUINAS, SISTEMAS E INSTRUMENTOS", codigo: "3144"},
  {nome: "TÉCNICOS EM METALURGIA (ESTRUTURAS METÁLICAS)", codigo: "3146"},
  {nome: "TÉCNICOS EM SIDERURGIA", codigo: "3147"},
  {nome: "TÉCNICOS EM GEOLOGIA, GEOTECNOLOGIA E GEOFÍSICA", codigo: "3161"},
  {nome: "TÉCNICOS EM GEODÉSIA E CARTOGRAFIA", codigo: "3162"},
  {nome: "TÉCNICOS EM MINERAÇÃO", codigo: "3163"},
  {nome: "TÉCNICOS EM PROGRAMAÇÃO", codigo: "3171"},
  {nome: "TÉCNICOS EM OPERAÇÃO DE COMPUTADORES", codigo: "3172"},
  {nome: "DESENHISTAS TÉCNICOS E MODELISTAS", codigo: "3189"},
  {nome: "TÉCNICOS DO VESTUÁRIO", codigo: "3191"},
  {nome: "TÉCNICOS DO MOBILIÁRIO E AFINS", codigo: "3192"},
  {nome: "TÉCNICOS EM BIOLOGIA ", codigo: "3201"},
  {nome: "TÉCNICOS AGROPECUÁRIOS", codigo: "3210"},
  {nome: "TÉCNICOS AGRÍCOLAS", codigo: "3211"},
  {nome: "TÉCNICOS DA PECUÁRIA", codigo: "3212"},
  {nome: "TÉCNICOS FLORESTAIS", codigo: "3213"},
  {nome: "TÉCNICOS DA PISCICULTURA", codigo: "3214"},
  {nome: "TÉCNICOS EM FISIOTERAPIA E AFINS", codigo: "3221"},
  {nome: "TÉCNICOS E AUXILIARES DE ENFERMAGEM", codigo: "3222"},
  {nome: "ORTOPTISTAS E ÓTICOS", codigo: "3223"},
  {nome: "TÉCNICOS DE ODONTOLOGIA", codigo: "3224"},
  {nome: "TÉCNICOS DA FABRICAÇÃO DE APARELHOS LOCOMOTORES", codigo: "3225"},
  {nome: "TÉCNICOS EM VETERINÁRIA", codigo: "3231"},
  {nome: "TÉCNICOS ZOOTECNISTAS", codigo: "3232"},
  {nome: "OPERADORES DE EQUIPAMENTOS MÉDICOS E ODONTOLÓGICOS", codigo: "3241"},
  {nome: "TÉCNICOS DE LABORATÓRIO DE ANÁLISES CLÍNICAS", codigo: "3242"},
  {nome: "TESTADORES SENSORIAIS", codigo: "3250"},
  {nome: "TÉCNICOS EM FARMÁCIA", codigo: "3251"},
  {nome: "TÉCNICOS EM PRODUÇÃO E CONSERVAÇÃO DE ALIMENTOS", codigo: "3252"},
  {nome: "TÉCNICOS DE APOIO À BIOTECNOLOGIA ", codigo: "3253"},
  {nome: "EMBALSAMADORES E TAXIDERMISTAS", codigo: "3281"},
  {nome: "PROFESSORES NA EDUCAÇÃO INFANTIL (COM FORMAÇÃO DE NÍVEL MÉDIO)", codigo: "3311"},
  {nome: "PROFESSORES NO ENSINO FUNDAMENTAL (COM FORMAÇÃO DE NÍVEL MÉDIO)", codigo: "3312"},
  {nome: "PROFESSORES NO ENSINO PROFISSIONALIZANTE (COM FORMAÇÃO DE NÍVEL MÉDIO)", codigo: "3313"},
  {nome: "PROFESSORES LEIGOS NA EDUCAÇÃO INFANTIL E NO ENSINO FUNDAMENTAL", codigo: "3321"},
  {nome: "PROFESSORES LEIGOS NO ENSINO PROFISSIONALIZANTE", codigo: "3322"},
  {nome: "INSTRUTORES E PROFESSORES DE ESCOLAS LIVRES", codigo: "3331"},
  {nome: "INSPETORES DE ALUNOS E AFINS", codigo: "3341"},
  {nome: "PILOTOS DE AVIAÇÃO COMERCIAL, NAVEGADORES, MECÂNICOS DE VÔO E AFINS", codigo: "3411"},
  {nome: "TÉCNICOS MARÍTIMOS, FLUVIÁRIOS E REGIONAIS DE CONVÉS", codigo: "3412"},
  {nome: "TÉCNICOS MARÍTIMOS, FLUVIÁRIOS E REGIONAIS DE MÁQUINAS", codigo: "3413"},
  {nome: "TÉCNICOS EM TRANSPORTES INTERMODAIS", codigo: "3421"},
  {nome: "TÉCNICOS EM TRANSPORTES (ADUANEIROS)", codigo: "3422"},
  {nome: "TÉCNICOS EM TRANSPORTES RODOVIÁRIOS", codigo: "3423"},
  {nome: "TÉCNICOS EM TRANSPORTES METROFERROVIÁRIOS", codigo: "3424"},
  {nome: "TÉCNICOS EM TRANSPORTES AEROVIÁRIOS", codigo: "3425"},
  {nome: "TÉCNICOS EM TRANSPORTES DE VIAS NAVEGÁVEIS", codigo: "3426"},
  {nome: "TÉCNICOS EM CONTABILIDADE", codigo: "3511"},
  {nome: "TÉCNICOS EM ESTATÍSTICA", codigo: "3512"},
  {nome: "TÉCNICOS EM ADMINISTRAÇÃO", codigo: "3513"},
  {nome: "SERVENTUÁRIOS DA JUSTIÇA E AFINS", codigo: "3514"},
  {nome: "TÉCNICOS E FISCAIS DE TRIBUTAÇÃO E ARRECADAÇÃO", codigo: "3515"},
  {nome: "TÉCNICOS DE SEGURANÇA DE TRABALHO", codigo: "3516"},
  {nome: "TÉCNICOS E ANALISTAS DE SEGUROS E AFINS", codigo: "3517"},
  {nome: "INSPETORES DE POLÍCIA E DETETIVES", codigo: "3518"},
  {nome: "AGENTES DA SAÚDE E DO MEIO AMBIENTE", codigo: "3522"},
  {nome: "AGENTES DE INSPEÇÃO DE PESOS E MEDIDAS", codigo: "3523"},
  {nome: "AGENTES DE FISCALIZAÇÃO DE ESPETÁCULOS E MEIOS DE COMUNICAÇÃO", codigo: "3524"},
  {nome: "AGENTES SINDICAIS E DE INSPEÇÃO DO TRABALHO", codigo: "3525"},
  {nome: "AGENTES DE BOLSA, CÂMBIO E OUTROS SERVIÇOS FINANCEIROS", codigo: "3531"},
  {nome: "TÉCNICOS DE OPERAÇÕES E SERVIÇOS BANCÁRIOS", codigo: "3532"},
  {nome: "REPRESENTANTES COMERCIAIS E TÉCNICOS DE VENDAS", codigo: "3541"},
  {nome: "COMPRADORES", codigo: "3542"},
  {nome: "TÉCNICOS EM EXPORTAÇÃO E IMPORTAÇÃO", codigo: "3543"},
  {nome: "LEILOEIROS E AVALIADORES", codigo: "3544"},
  {nome: "CORRETORES DE SEGUROS", codigo: "3545"},
  {nome: "CORRETORES DE IMÓVEIS", codigo: "3546"},
  {nome: "CORRETORES DE TÍTULOS E VALORES", codigo: "3547"},
  {nome: "TÉCNICOS EM TURISMO", codigo: "3548"},
  {nome: "TÉCNICOS EM BIBLIOTECONOMIA", codigo: "3711"},
  {nome: "TÉCNICOS EM MUSEOLOGIA", codigo: "3712"},
  {nome: "TÉCNICOS EM ARTES GRÁFICAS", codigo: "3713"},
  {nome: "CINEGRAFISTAS", codigo: "3721"},
  {nome: "FOTÓGRAFOS", codigo: "3722"},
  {nome: "TÉCNICOS EM OPERAÇÃO DE MÁQUINAS DE TRANSMISSÃO DE DADOS", codigo: "3723"},
  {nome: "TÉCNICOS EM OPERAÇÃO DE ESTAÇÃO DE RÁDIO", codigo: "3731"},
  {nome: "TÉCNICOS EM OPERAÇÃO DE ESTAÇÃO DE TELEVISÃO", codigo: "3732"},
  {nome: "TÉCNICOS EM OPERAÇÃO DE APARELHOS DE SONORIZAÇÃO", codigo: "3741"},
  {nome: "TÉCNICOS EM OPERAÇÃO DE APARELHOS DE CENOGRAFIA", codigo: "3742"},
  {nome: "TÉCNICOS EM OPERAÇÃO DE APARELHOS DE PROJEÇÃO", codigo: "3743"},
  {nome: "DECORADORES E VITRINISTAS DE NÍVEL MÉDIO", codigo: "3751"},
  {nome: "BAILARINOS DE DANÇAS POPULARES", codigo: "3761"},
  {nome: "MÚSICOS E CANTORES POPULARES", codigo: "3762"},
  {nome: "PALHAÇOS, ACROBATAS E AFINS", codigo: "3763"},
  {nome: "APRESENTADORES DE ESPETÁCULOS", codigo: "3764"},
  {nome: "MODELOS", codigo: "3765"},
  {nome: "TÉCNICOS ESPORTIVOS", codigo: "3771"},
  {nome: "ATLETAS PROFISSIONAIS", codigo: "3772"},
  {nome: "ÁRBITROS DESPORTIVOS", codigo: "3773"},
  {nome: "TÉCNICOS DE PLANEJAMENTO DE PRODUÇÃO", codigo: "3911"},
  {nome: "TÉCNICOS DE CONTROLE DA PRODUÇÃO", codigo: "3912"},
  {nome: "SUPERVISORES DE SERVIÇOS ADMINISTRATIVOS (EXCETO CONTABILIDADE E CONTROLE)", codigo: "4101"},
  {nome: "SUPERVISORES DE SERVIÇOS CONTÁBEIS, FINANCEIROS E DE CONTROLE", codigo: "4102"},
  {nome: "ESCRITURÁRIOS EM GERAL, AGENTES, ASSISTENTES E AUXILIARES ADMINISTRATIVOS", codigo: "4110"},
  {nome: "SECRETÁRIOS DE EXPEDIENTE E ESTENÓGRAFOS", codigo: "4121"},
  {nome: "OPERADORES DE MÁQUINAS DE ESCRITÓRIO", codigo: "4122"},
  {nome: "CONTÍNUOS", codigo: "4123"},
  {nome: "ESCRITURÁRIOS DE CONTABILIDADE", codigo: "4131"},
  {nome: "ESCRITURÁRIOS DE FINANÇAS", codigo: "4132"},
  {nome: "ALMOXARIFES E ARMAZENISTAS", codigo: "4141"},
  {nome: "ESCRITURÁRIOS DE APOIO À PRODUÇÃO", codigo: "4142"},
  {nome: "ESCRITURÁRIOS DE SERVIÇOS DE BIBLIOTECA E DOCUMENTAÇÃO ", codigo: "4151"},
  {nome: "CARTEIROS E AFINS", codigo: "4152"},
  {nome: "SUPERVISORES DE TRABALHADORES DE ATENDIMENTO AO PÚBLICO", codigo: "4201"},
  {nome: "CAIXAS E BILHETEIROS (EXCETO CAIXAS DE BANCO)", codigo: "4211"},
  {nome: "CAIXAS DE BANCO E OPERADORES DE CÂMBIO", codigo: "4212"},
  {nome: "COLETADORES DE APOSTAS E DE JOGOS", codigo: "4213"},
  {nome: "COBRADORES E AFINS (EXCETO NOS TRANSPORTES PÚBLICOS)", codigo: "4214"},
  {nome: "RECEPCIONISTAS", codigo: "4221"},
  {nome: "TELEFONISTAS", codigo: "4222"},
  {nome: "OPERADORES DE TELEMARKETING", codigo: "4223"},
  {nome: "DESPACHANTES DE DOCUMENTOS", codigo: "4231"},
  {nome: "ENTREVISTADORES, RECENSEADORES E AFINS", codigo: "4241"},
  {nome: "SUPERVISORES DOS SERVIÇOS DE TRANSPORTE, TURISMO, HOTELARIA E ADMINISTRAÇÃO DE EDIFÍCIOS", codigo: "5101"},
  {nome: "SUPERVISORES DOS SERVIÇOS DE SAÚDE E CUIDADOS PESSOAIS", codigo: "5102"},
  {nome: "SUPERVISORES DOS SERVIÇOS DE PROTEÇÃO, SEGURANÇA E OUTROS SERVIÇOS", codigo: "5103"},
  {nome: "TRABALHADORES DOS SERVIÇOS DIRETO AOS PASSAGEIROS", codigo: "5111"},
  {nome: "FISCAIS E COBRADORES DOS TRANSPORTES PÚBLICOS", codigo: "5112"},
  {nome: "GUIAS DE TURISMO", codigo: "5114"},
  {nome: "TRABALHADORES DOS SERVIÇOS DOMÉSTICOS EM GERAL", codigo: "5121"},
  {nome: "MORDOMOS E GOVERNANTAS", codigo: "5131"},
  {nome: "COZINHEIROS", codigo: "5132"},
  {nome: "CAMAREIROS, ROUPEIROS E AFINS", codigo: "5133"},
  {nome: "GARÇONS, BARMEN E COPEIROS", codigo: "5134"},
  {nome: "TRABALHADORES NOS SERVIÇOS DE ADMINISTRAÇÃO DE EDIFÍCIOS", codigo: "5141"},
  {nome: "TRABALHADORES NOS SERVIÇOS DE MANUTENÇÃO E CONSERVAÇÃO DE EDIFÍCIOS E LOGRADOUROS", codigo: "5142"},
  {nome: "ATENDENTES DE ENFERMAGEM, PARTEIRAS PRÁTICAS E AFINS", codigo: "5151"},
  {nome: "AUXILIARES DE LABORATÓRIO DE SAÚDE", codigo: "5152"},
  {nome: "TRABALHADORES NOS SERVIÇOS DE HIGIENE E EMBELEZAMENTO", codigo: "5161"},
  {nome: "ATENDENTES DE CRECHE E ACOMPANHANTES DE IDOSOS", codigo: "5162"},
  {nome: "TRABALHADORES DOS SERVIÇOS FUNERÁRIOS", codigo: "5165"},
  {nome: "TRABALHADORES AUXILIARES DOS SERVIÇOS FUNERÁRIOS", codigo: "5166"},
  {nome: "ASTRÓLOGOS E ADIVINHOS", codigo: "5167"},
  {nome: "TINTUREIROS, LAVADEIROS E AFINS, À MÁQUINA E À MÃO", codigo: "5169"},
  {nome: "BOMBEIROS (EXCETO DO CORPO DE BOMBEIROS MILITAR)", codigo: "5171"},
  {nome: "POLICIAIS E GUARDAS DE TRÂNSITO", codigo: "5172"},
  {nome: "VIGILANTES E GUARDAS DE SEGURANÇA", codigo: "5173"},
  {nome: "GUARDAS E VIGIAS", codigo: "5174"},
  {nome: "ENTREGADORES EXTERNOS (EXCETO CARTEIROS)", codigo: "5191"},
  {nome: "CATADORES DE SUCATA", codigo: "5192"},
  {nome: "TRABALHADORES DO SEXO", codigo: "5198"},
  {nome: "OUTROS TRABALHADORES DOS SERVIÇOS", codigo: "5199"},
  {nome: "SUPERVISORES DE VENDAS E DE PRESTAÇÃO DE SERVIÇOS DO COMÉRCIO", codigo: "5201"},
  {nome: "VENDEDORES E DEMONSTRADORES EM LOJAS OU MERCADOS", codigo: "5211"},
  {nome: "REPOSITORES E REMARCADORES DO COMÉRCIO", codigo: "5221"},
  {nome: "INSTALADORES DE PRODUTOS E ACESSÓRIOS", codigo: "5231"},
  {nome: "VENDEDORES A DOMICÍLIO", codigo: "5241"},
  {nome: "VENDEDORES EM QUIOSQUES E BARRACAS", codigo: "5242"},
  {nome: "VENDEDORES AMBULANTES", codigo: "5243"},
  {nome: "PRODUTORES AGROPECUÁRIOS EM GERAL", codigo: "6110"},
  {nome: "PRODUTORES AGRÍCOLAS ", codigo: "6129"},
  {nome: "PRODUTORES EM PECUÁRIA ", codigo: "6139"},
  {nome: "SUPERVISORES NA EXPLORAÇÃO AGROPECUÁRIA", codigo: "6201"},
  {nome: "TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA EM GERAL", codigo: "6210"},
  {nome: "TRABALHADORES AGRÍCOLAS ", codigo: "6229"},
  {nome: "TRABALHADORES NA PECUÁRIA ", codigo: "6239"},
  {nome: "SUPERVISORES NA EXPLORAÇÃO FLORESTAL, CAÇA E PESCA", codigo: "6301"},
  {nome: "PESCADORES E CAÇADORES", codigo: "6319"},
  {nome: "EXTRATIVISTAS FLORESTAIS ", codigo: "6329"},
  {nome: "TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA", codigo: "6410"},
  {nome: "TRABALHADORES DA MECANIZAÇÃO FLORESTAL", codigo: "6420"},
  {nome: "TRABALHADORES DA IRRIGAÇÃO E DRENAGEM", codigo: "6430"},
  {nome: "SUPERVISORES DA EXTRAÇÃO MINERAL ", codigo: "7101"},
  {nome: "SUPERVISORES DA CONSTRUÇÃO CIVIL", codigo: "7102"},
  {nome: "TRABALHADORES DA EXTRAÇÃO DE MINERAIS SÓLIDOS - MINEIROS E AFINS", codigo: "7111"},
  {nome: "TRABALHADORES DA EXTRAÇÃO DE MINERAIS SÓLIDOS - OPERADORES DE MÁQUINA", codigo: "7112"},
  {nome: "TRABALHADORES DA EXTRAÇÃO DE MINERAIS LÍQUIDOS E GASOSOS", codigo: "7113"},
  {nome: "GARIMPEIROS E OPERADORES DE SALINAS", codigo: "7114"},
  {nome: "TRABALHADORES DE BENEFICIAMENTO DE MINÉRIOS", codigo: "7121"},
  {nome: "TRABALHADORES DE BENEFICIAMENTO DE PEDRAS", codigo: "7122"},
  {nome: "TRABALHADORES DE TERRAPLENAGEM E FUNDAÇÕES", codigo: "7151"},
  {nome: "TRABALHADORES DE ESTRUTURAS DE ALVENARIA", codigo: "7152"},
  {nome: "TRABALHADORES DE ESTRUTURAS DE CONCRETO ARMADO", codigo: "7153"},
  {nome: "TRABALHADORES NA OPERAÇÃO DE MÁQUINAS DE CONCRETO ARMADO", codigo: "7154"},
  {nome: "TRABALHADORES DE MONTAGEM DE ESTRUTURAS DE MADEIRA, METAL E COMPÓSITOS (OBRAS CIVIS E AFINS)", codigo: "7155"},
  {nome: "TRABALHADORES DE INSTALAÇÕES ELÉTRICAS", codigo: "7156"},
  {nome: "TRABALHADORES DE INSTALAÇÕES DE MATERIAIS ISOLANTES", codigo: "7157"},
  {nome: "REVESTIDORES DE CONCRETO ARMADO (REVESTIMENTOS RÍGIDOS)", codigo: "7161"},
  {nome: "TELHADORES (REVESTIMENTOS RÍGIDOS)", codigo: "7162"},
  {nome: "VIDRACEIROS (REVESTIMENTOS RÍGIDOS)", codigo: "7163"},
  {nome: "ESTUCADORES E GESSEIROS", codigo: "7164"},
  {nome: "APLICADORES DE REVESTIMENTOS CERÂMICOS, PASTILHAS, PEDRAS E MADEIRAS", codigo: "7165"},
  {nome: "PINTORES DE OBRAS E REVESTIDORES DE INTERIORES (REVESTIMENTOS FLEXÍVEIS)", codigo: "7166"},
  {nome: "AJUDANTES DE OBRAS CIVIS", codigo: "7170"},
  {nome: "SUPERVISORES DE USINAGEM, CONFORMAÇÃO E TRATAMENTO DE METAIS", codigo: "7201"},
  {nome: "SUPERVISORES DE MONTAGEM METALMECÂNICA", codigo: "7202"},
  {nome: "FERRAMENTEIROS E AFINS", codigo: "7211"},
  {nome: "PREPARADORES E OPERADORES DE MÁQUINAS - FERRAMENTA CONVENCIONAL", codigo: "7212"},
  {nome: "OPERADORES DE USINAGEM CONVENCIONAL (PRODUÇÃO EM SÉRIE)", codigo: "7213"},
  {nome: "AFIADORES E POLIDORES DE METAIS", codigo: "7214"},
  {nome: "OPERADORES DE MÁQUINAS E CENTROS DE USINAGEM CNC ", codigo: "7215"},
  {nome: "TRABALHADORES DE FORJAMENTO DE METAIS", codigo: "7221"},
  {nome: "TRABALHADORES DE FUNDIÇÃO DE METAIS E DE COMPÓSITOS", codigo: "7222"},
  {nome: "TRABALHADORES DE MOLDAGEM DE METAIS E DE COMPÓSITOS", codigo: "7223"},
  {nome: "TRABALHADORES DE TREFILAÇÃO, ESTIRAMENTO E EXTRUSÃO DE METAIS E DE COMPÓSITOS", codigo: "7224"},
  {nome: "TRABALHADORES DE TRATAMENTO TÉRMICO DE METAIS E DE COMPÓSITOS", codigo: "7231"},
  {nome: "TRABALHADORES DE TRATAMENTO DE SUPERFÍCIES DE METAIS E DE COMPÓSITOS (TERMOQUÍMICOS)", codigo: "7232"},
  {nome: "TRABALHADORES DA PINTURA DE EQUIPAMENTOS, VEÍCULOS, ESTRUTURAS METÁLICAS E DE COMPÓSITOS", codigo: "7233"},
  {nome: "ENCANADORES E INSTALADORES DE TUBULAÇÕES", codigo: "7241"},
  {nome: "TRABALHADORES DE TRAÇAGEM E MONTAGEM DE ESTRUTURA METÁLICA E DE COMPÓSITOS", codigo: "7242"},
  {nome: "TRABALHADORES DE SOLDAGEM E CORTE DE METAIS E DE COMPÓSITOS", codigo: "7243"},
  {nome: "TRABALHADORES DE CALDEIRARIA E SERRALHERIA", codigo: "7244"},
  {nome: "OPERADORES DE MÁQUINAS DE CONFORMAÇÃO DE METAIS", codigo: "7245"},
  {nome: "APARELHADORES E EMENDADORES DE CABOS (EXCETO CABOS ELÉTRICOS E DE TELECOMUNICAÇÕES)", codigo: "7246"},
  {nome: "AJUSTADORES MECÂNICOS POLIVALENTES", codigo: "7250"},
  {nome: "MONTADORES DE APARELHOS E ACESSÓRIOS MECÂNICOS EM LINHAS DE MONTAGEM ", codigo: "7251"},
  {nome: "MONTADORES DE MÁQUINAS INDUSTRIAIS", codigo: "7252"},
  {nome: "MONTADORES DE MÁQUINAS PESADAS", codigo: "7253"},
  {nome: "MONTADORES DE MOTORES E TURBINAS", codigo: "7254"},
  {nome: "MONTADORES DE VEÍCULOS AUTOMOTORES (LINHA DE MONTAGEM)", codigo: "7255"},
  {nome: "MONTADORES DE SISTEMAS E ESTRUTURAS DE AERONAVES", codigo: "7256"},
  {nome: "MONTADORES DE INSTALAÇÕES DE VENTILAÇÃO E REFRIGERAÇÃO", codigo: "7257"},
  {nome: "SUPERVISORES DE MONTAGENS E INSTALAÇÕES ELETROELETRÔNICAS", codigo: "7301"},
  {nome: "MONTADORES DE EQUIPAMENTOS ELETROELETRÔNICOS", codigo: "7311"},
  {nome: "MONTADORES DE APARELHOS DE TELECOMUNICAÇÕES", codigo: "7312"},
  {nome: "INSTALADORES-REPARADORES DE APARELHOS DE TELECOMUNICAÇÕES", codigo: "7313"},
  {nome: "INSTALADORES E REPARADORES DE LINHAS E CABOS ELÉTRICOS, TELEFÔNICOS E DE COMUNICAÇÃO DE DADOS", codigo: "7321"},
  {nome: "SUPERVISORES DA MECÂNICA DE PRECISÃO E INSTRUMENTOS MUSICAIS", codigo: "7401"},
  {nome: "MECÂNICOS DE INSTRUMENTOS DE PRECISÃO (EXCETO TÉCNICOS)", codigo: "7411"},
  {nome: "CONFECCIONADORES DE INSTRUMENTOS MUSICAIS", codigo: "7421"},
  {nome: "SUPERVISORES DE JOALHERIA E AFINS", codigo: "7501"},
  {nome: "SUPERVISORES DE VIDRARIA, CERÂMICA E AFINS", codigo: "7502"},
  {nome: "JOALHEIROS E ARTESÃOS DE METAIS PRECIOSOS E SEMI-PRECIOSOS", codigo: "7519"},
  {nome: "SOPRADORES E MOLDADORES DE VIDROS E AFINS", codigo: "7521"},
  {nome: "CORTADORES, POLIDORES, JATEADORES E GRAVADORES DE VIDROS E AFINS", codigo: "7522"},
  {nome: "CERAMISTAS (PREPARAÇÃO E FABRICAÇÃO)", codigo: "7523"},
  {nome: "VIDREIROS E CERAMISTAS (ACABAMENTO E DECORAÇÃO)", codigo: "7524"},
  {nome: "SUPERVISORES DA INDÚSTRIA TÊXTIL", codigo: "7601"},
  {nome: "SUPERVISORES DA INDÚSTRIA DO CURTIMENTO", codigo: "7602"},
  {nome: "SUPERVISORES DA INDÚSTRIA DE CONFECÇÃO DE ROUPAS", codigo: "7603"},
  {nome: "SUPERVISORES DA INDÚSTRIA DE CONFECÇÃO DE CALÇADOS", codigo: "7604"},
  {nome: "SUPERVISORES DA CONFECÇÃO DE ARTEFATOS DE TECIDOS, COUROS E AFINS", codigo: "7605"},
  {nome: "SUPERVISORES DAS ARTES GRÁFICAS", codigo: "7606"},
  {nome: "TRABALHADORES POLIVALENTES DAS INDÚSTRIAS TÊXTEIS", codigo: "7610"},
  {nome: "TRABALHADORES DA PREPARAÇÃO DA TECELAGEM", codigo: "7611"},
  {nome: "OPERADORES DA PREPARAÇÃO DA TECELAGEM", codigo: "7612"},
  {nome: "OPERADORES DE TEAR E MÁQUINAS SIMILARES", codigo: "7613"},
  {nome: "TRABALHADORES DE ACABAMENTO, TINGIMENTO E ESTAMPARIA DAS INDÚSTRIAS TÊXTEIS", codigo: "7614"},
  {nome: "INSPETORES E REVISORES DE PRODUÇÃO TÊXTIL", codigo: "7618"},
  {nome: "TRABALHADORES POLIVALENTES DO CURTIMENTO DE COUROS E PELES", codigo: "7620"},
  {nome: "TRABALHADORES DA PREPARAÇÃO DE PELES", codigo: "7621"},
  {nome: "TRABALHADORES DO CURTIMENTO DE COUROS E PELES", codigo: "7622"},
  {nome: "TRABALHADORES DO ACABAMENTO DE COUROS E PELES", codigo: "7623"},
  {nome: "TRABALHADORES POLIVALENTES DAS INDÚSTRIAS DA CONFECÇÃO DE ROUPAS", codigo: "7630"},
  {nome: "TRABALHADORES DA PREPARAÇÃO DA CONFECÇÃO DE ROUPAS", codigo: "7631"},
  {nome: "OPERADORES DE MÁQUINAS DE COSTURA DE ROUPAS", codigo: "7632"},
  {nome: "OPERADORES DE MÁQUINAS DE COSTURAS - ACABAMENTO DE ROUPAS", codigo: "7633"},
  {nome: "TRABALHADORES POLIVALENTES DA CONFECÇÃO DE CALÇADOS", codigo: "7640"},
  {nome: "TRABALHADORES DA PREPARAÇÃO DA CONFECÇÃO DE CALÇADOS", codigo: "7641"},
  {nome: "OPERADORES DE MÁQUINAS DE COSTURAR CALÇADOS", codigo: "7642"},
  {nome: "OPERADORES DE ACABAMENTO DE CALÇADOS", codigo: "7643"},
  {nome: "TRABALHADORES POLIVALENTES DA CONFECÇÃO DE ARTEFATOS DE TECIDOS E COUROS", codigo: "7650"},
  {nome: "TRABALHADORES DA PREPARAÇÃO DE ARTEFATOS DE TECIDOS E COUROS", codigo: "7651"},
  {nome: "TRABALHADORES DA FABRICAÇÃO DE ARTEFATOS DE TECIDOS E COUROS", codigo: "7652"},
  {nome: "OPERADORES DE MÁQUINAS NA FABRICAÇÃO DE ARTEFATOS DE TECIDOS E COUROS", codigo: "7653"},
  {nome: "TRABALHADORES DO ACABAMENTO DE ARTEFATOS DE TECIDOS E COUROS", codigo: "7654"},
  {nome: "TRABALHADORES POLIVALENTES DAS ARTES GRÁFICAS", codigo: "7660"},
  {nome: "TRABALHADORES DA PRÉ-IMPRESSÃO GRÁFICA", codigo: "7661"},
  {nome: "TRABALHADORES DA IMPRESSÃO GRÁFICA", codigo: "7662"},
  {nome: "TRABALHADORES DO ACABAMENTO GRÁFICO ", codigo: "7663"},
  {nome: "TRABALHADORES DE LABORATÓRIO FOTOGRÁFICO", codigo: "7664"},
  {nome: "TRABALHADORES ARTESANAIS DA TECELAGEM", codigo: "7681"},
  {nome: "TRABALHADORES ARTESANAIS DA CONFECÇÃO DE ROUPAS", codigo: "7682"},
  {nome: "TRABALHADORES ARTESANAIS DA CONFECÇÃO DE CALÇADOS E ARTEFATOS DE COUROS E PELES", codigo: "7683"},
  {nome: "TRABALHADORES TIPOGRÁFICOS, LINOTIPISTAS E AFINS", codigo: "7686"},
  {nome: "ENCADERNADORES E RECUPERADORES DE LIVROS (PEQUENOS LOTES OU A UNIDADE)", codigo: "7687"},
  {nome: "SUPERVISORES DA INDÚSTRIA DA MADEIRA, MOBILIÁRIO E DA CARPINTARIA VEICULAR", codigo: "7701"},
  {nome: "MARCENEIROS E AFINS", codigo: "7711"},
  {nome: "TRABALHADORES DE TRATAMENTO E PREPARAÇÃO DE MADEIRAS", codigo: "7721"},
  {nome: "OPERADORES DE MÁQUINAS DE DESDOBRAMENTO DE MADEIRAS", codigo: "7731"},
  {nome: "OPERADORES DE LAMINAÇÃO, AGLOMERAÇÃO E PRENSAGEM DE CHAPAS", codigo: "7732"},
  {nome: "PREPARADORES E OPERADORES DE USINAGEM DE MADEIRAS CONVENCIONAL", codigo: "7733"},
  {nome: "OPERADORES DE MÁQUINAS DE MADEIRA (PRODUÇÃO EM SÉRIE)", codigo: "7734"},
  {nome: "OPERADORES DE MÁQUINAS E CENTROS DE USINAGEM DE MADEIRA CNC", codigo: "7735"},
  {nome: "MONTADORES DE MÓVEIS E ARTEFATOS DE MADEIRA", codigo: "7741"},
  {nome: "TRABALHADORES DO ACABAMENTO DE MADEIRA E DO MOBILIÁRIO", codigo: "7751"},
  {nome: "CONFECCIONADORES DE ARTEFATOS DE MADEIRA, MÓVEIS DE VIME E AFINS", codigo: "7764"},
  {nome: "CARPINTEIROS NAVAIS E DE AERONAVES", codigo: "7771"},
  {nome: "CARPINTEIROS DE CARROCERIAS E CARRETAS", codigo: "7772"},
  {nome: "SUPERVISORES DE EMBALAGEM E ETIQUETAGEM", codigo: "7801"},
  {nome: "OPERADORES DE ROBÔS INDUSTRIAIS", codigo: "7811"},
  {nome: "OPERADORES DE VEÍCULOS OPERADOS E CONTROLADOS REMOTAMENTE (ROV, RCV)", codigo: "7813"},
  {nome: "TRABALHADORES SUBAQUÁTICOS", codigo: "7817"},
  {nome: "CONDUTORES E OPERADORES POLIVALENTES", codigo: "7820"},
  {nome: "OPERADORES DE EQUIPAMENTOS DE ELEVAÇÃO", codigo: "7821"},
  {nome: "OPERADORES DE EQUIPAMENTOS DE MOVIMENTAÇÃO DE CARGAS", codigo: "7822"},
  {nome: "CONDUTORES DE VEÍCULOS SOBRE RODAS (TRANSPORTE PARTICULAR)", codigo: "7823"},
  {nome: "CONDUTORES DE VEÍCULOS SOBRE RODAS (TRANSPORTE COLETIVO)", codigo: "7824"},
  {nome: "CONDUTORES DE VEÍCULOS SOBRE RODAS (DISTRIBUIDOR DE MERCADORIAS)", codigo: "7825"},
  {nome: "CONDUTORES DE VEÍCULOS SOBRE TRILHOS", codigo: "7826"},
  {nome: "TRABALHADORES NA NAVEGAÇÃO MARÍTIMA FLUVIAL E REGIONAL", codigo: "7827"},
  {nome: "CONDUTORES DE VEÍCULOS DE TRAÇÃO ANIMAL E DE PEDAIS", codigo: "7828"},
  {nome: "TRABALHADORES DE MANOBRAS DE TRANSPORTE SOBRE TRILHOS", codigo: "7831"},
  {nome: "TRABALHADORES DE CARGAS E DESCARGAS DE MERCADORIAS", codigo: "7832"},
  {nome: "TRABALHADORES DE EMBALAGEM E DE ETIQUETAGEM", codigo: "7841"},
  {nome: "ALIMENTADORES DE LINHAS DE PRODUÇÃO", codigo: "7842"},
  {nome: "SUPERVISORES DAS INDÚSTRIAS QUÍMICAS, PETROQUÍMICAS E AFINS", codigo: "8101"},
  {nome: "SUPERVISORES DA INDÚSTRIA DE PLÁSTICOS E BORRACHA ", codigo: "8102"},
  {nome: "SUPERVISORES DA INDÚSTRIA DE PRODUTOS FARMACÊUTICOS, COSMÉTICOS E AFINS", codigo: "8103"},
  {nome: "OPERADORES POLIVALENTES DE INSTALAÇÕES QUÍMICAS, PETROQUÍMICAS E AFINS", codigo: "8110"},
  {nome: "OPERADORES DE MOAGEM E MISTURA DE MATERIAIS (TRATAMENTOS QUÍMICOS E AFINS)", codigo: "8111"},
  {nome: "OPERADORES DE PROCESSOS TERMOQUÍMICOS E AFINS", codigo: "8112"},
  {nome: "OPERADORES DE FILTRAGEM E SEPARAÇÃO", codigo: "8113"},
  {nome: "OPERADORES DE DESTILAÇÃO E REAÇÃO", codigo: "8114"},
  {nome: "OPERADORES DE PRODUÇÃO E REFINO DE PETRÓLEO E GÁS", codigo: "8115"},
  {nome: "OPERADORES DE COQUEIFICAÇÃO", codigo: "8116"},
  {nome: "OPERADORES DE INSTALAÇÕES E MÁQUINAS DE PRODUTOS PLÁSTICOS, DE BORRACHA E PARAFINAS", codigo: "8117"},
  {nome: "OPERADORES DE MÁQUINAS E INSTALAÇÕES DE PRODUTOS FARMACÊUTICOS, COSMÉTICOS E AFINS ", codigo: "8118"},
  {nome: "TRABALHADORES DA FABRICAÇÃO DE MUNIÇÃO E EXPLOSIVOS QUÍMICOS", codigo: "8121"},
  {nome: "OPERADORES DE OUTRAS INSTALAÇÕES QUÍMICAS, PETROQUÍMICAS E AFINS", codigo: "8131"},
  {nome: "LABORATORISTAS INDUSTRIAIS AUXILIARES", codigo: "8181"},
  {nome: "SUPERVISORES DA SIDERURGIA", codigo: "8201"},
  {nome: "SUPERVISORES DE MATERIAIS DE CONSTRUÇÃO (VIDRO, CERÂMICA E COMPÓSITOS)", codigo: "8202"},
  {nome: "OPERADORES DE INSTALAÇÕES DE SINTERIZAÇÃO", codigo: "8211"},
  {nome: "OPERADORES DE FORNOS DE 1ª FUSÃO E ACIARIA", codigo: "8212"},
  {nome: "OPERADORES DE LAMINAÇÃO", codigo: "8213"},
  {nome: "OPERADORES DE ACABAMENTO DE CHAPAS E METAIS", codigo: "8214"},
  {nome: "FORNEIROS METALÚRGICOS (2ª FUSÃO E REAQUECIMENTO)", codigo: "8221"},
  {nome: "OPERADORES DE PREPARAÇÃO DE MASSAS PARA VIDRO, CERÂMICA, PORCELANA E MATERIAIS DE CONSTRUÇÃO", codigo: "8231"},
  {nome: "OPERADORES DE INSTALAÇÕES E EQUIPAMENTOS DE FABRICAÇÃO DE CERÂMICAS, VIDROS E PORCELANAS", codigo: "8232"},
  {nome: "OPERADORES DE INSTALAÇÕES E EQUIPAMENTOS DE FABRICAÇÃO DE MATERIAIS DE CONSTRUÇÃO", codigo: "8233"},
  {nome: "TRABALHADORES ARTESANAIS DE MATERIAIS DE CONSTRUÇÃO", codigo: "8281"},
  {nome: "SUPERVISORES DA FABRICAÇÃO DE CELULOSE E PAPEL", codigo: "8301"},
  {nome: "PREPARADORES DE PASTA PARA FABRICAÇÃO DE PAPEL", codigo: "8311"},
  {nome: "OPERADORES DE MÁQUINAS DE FABRICAR PAPEL E PAPELÃO", codigo: "8321"},
  {nome: "CONFECCIONADORES DE PRODUTOS DE PAPEL E PAPELÃO", codigo: "8339"},
  {nome: "SUPERVISORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO ", codigo: "8401"},
  {nome: "MOLEIROS", codigo: "8411"},
  {nome: "TRABALHADORES DO REFINO DO SAL", codigo: "8412"},
  {nome: "TRABALHADORES DA FABRICAÇÃO E REFINO DO AÇÚCAR", codigo: "8413"},
  {nome: "TRABALHADORES DA PREPARAÇÃO DE CAFÉ, CACAU E PRODUTOS AFINS", codigo: "8416"},
  {nome: "TRABALHADORES DA FABRICAÇÃO DE CACHAÇA, CERVEJA, VINHOS E OUTRAS BEBIDAS", codigo: "8417"},
  {nome: "PREPARADORES DE FUMO", codigo: "8421"},
  {nome: "CIGARREIROS", codigo: "8423"},
  {nome: "CHARUTEIROS E TRABALHADORES ARTESANAIS DA INDÚSTRIA DO FUMO", codigo: "8429"},
  {nome: "DEGUSTADORES", codigo: "8484"},
  {nome: "MAGAREFES E AFINS", codigo: "8485"},
  {nome: "TRABALHADORES DE FABRICAÇÃO E CONSERVAÇÃO DE ALIMENTOS (INCLUSIVE ARTESANAIS)", codigo: "8491"},
  {nome: "TRABALHADORES DA PASTEURIZAÇÃO DO LEITE, FABRICAÇÃO DE LATICÍNIOS E AFINS (INCLUSIVE ARTESANAIS)", codigo: "8492"},
  {nome: "PADEIROS, CONFEITEIROS E AFINS E OPERADORES NA FABRICAÇÃO DE PÃES, MASSAS E DOCES", codigo: "8493"},
  {nome: "SUPERVISORES DE INSTALAÇÕES DE PRODUÇÃO E DISTRIBUIÇÃO DE ENERGIA, UTILIDADES, CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO DE ÁGUA", codigo: "8601"},
  {nome: "OPERADORES DE INSTALAÇÕES DE GERAÇÃO DE ENERGIA TÉRMICA, ELÉTRICA E NUCLEAR", codigo: "8611"},
  {nome: "OPERADORES DE INSTALAÇÕES DE DISTRIBUIÇÃO DE ENERGIA TÉRMICA, ELÉTRICA E NUCLEAR", codigo: "8612"},
  {nome: "OPERADORES DE MÁQUINAS A VAPOR E CALDEIRAS", codigo: "8621"},
  {nome: "OPERADORES DE INSTALAÇÕES DE CAPTAÇÃO E DISTRIBUIÇÃO DE ÁGUAS", codigo: "8622"},
  {nome: "OPERADORES DE INSTALAÇÕES DE CAPTAÇÃO E TRATAMENTO DE ESGOTOS", codigo: "8623"},
  {nome: "OPERADORES DE INSTALAÇÕES DE CAPTAÇÃO, ENGARRAFAMENTO E DISTRIBUIÇÃO DE GASES", codigo: "8624"},
  {nome: "OPERADORES DE INSTALAÇÕES DE REFRIGERAÇÃO E AR CONDICIONADO", codigo: "8625"},
  {nome: "OUTROS TRABALHADORES ELEMENTARES INDUSTRIAIS ", codigo: "8711"},
  {nome: "SUPERVISORES DA REPARAÇÃO E MANUTENÇÃO DE MÁQUINAS E EQUIPAMENTOS INDUSTRIAIS, COMERCIAIS E RESIDENCIAIS", codigo: "9101"},
  {nome: "SUPERVISORES DA REPARAÇÃO E MANUTENÇÃO VEICULAR", codigo: "9102"},
  {nome: "SUPERVISORES DE OUTROS TRABALHADORES DA REPARAÇÃO, CONSERVAÇÃO E MANUTENÇÃO", codigo: "9109"},
  {nome: "MECÂNICOS DE MANUTENÇÃO DE BOMBAS, MOTORES, COMPRESSORES E EQUIPAMENTOS DE TRANSMISSÃO", codigo: "9111"},
  {nome: "MECÂNICOS DE MANUTENÇÃO DE APARELHOS TÉRMICOS, DE CLIMATIZAÇÃO E DE REFRIGERAÇÃO (EXCETO TÉCNICOS)", codigo: "9112"},
  {nome: "MECÂNICOS DE MANUTENÇÃO DE MÁQUINAS INDUSTRIAIS", codigo: "9113"},
  {nome: "MECÂNICOS DE MANUTENÇÃO DE MÁQUINAS PESADAS E EQUIPAMENTOS AGRÍCOLAS ", codigo: "9131"},
  {nome: "MECÂNICOS DE MANUTENÇÃO AERONÁUTICA", codigo: "9141"},
  {nome: "MECÂNICOS DE MANUTENÇÃO NAVAL (EM TERRA)", codigo: "9142"},
  {nome: "MECÂNICOS DE MANUTENÇÃO METROFERROVIÁRIA", codigo: "9143"},
  {nome: "MECÂNICOS DE MANUTENÇÃO DE VEÍCULOS AUTOMOTORES", codigo: "9144"},
  {nome: "REPARADORES DE INSTRUMENTOS DE MEDIÇÃO", codigo: "9151"},
  {nome: "REPARADORES DE INSTRUMENTOS MUSICAIS", codigo: "9152"},
  {nome: "REPARADORES DE EQUIPAMENTOS E INSTRUMENTOS MÉDICO-HOSPITALARES", codigo: "9153"},
  {nome: "REPARADORES DE EQUIPAMENTOS FOTOGRÁFICOS ", codigo: "9154"},
  {nome: "LUBRIFICADORES", codigo: "9191"},
  {nome: "TRABALHADORES DE MANUTENÇÃO DE MÁQUINAS PEQUENAS", codigo: "9192"},
  {nome: "MECÂNICOS DE MANUTENÇÃO DE BICICLETAS E EQUIPAMENTOS ESPORTIVOS E DE GINÁSTICA", codigo: "9193"},
  {nome: "SUPERVISORES DE MANUTENÇÃO ELETROELETRÔNICA INDUSTRIAL, COMERCIAL E RESIDENCIAL", codigo: "9501"},
  {nome: "SUPERVISORES DE MANUTENÇÃO ELETROELETRÔNICA VEICULAR", codigo: "9502"},
  {nome: "SUPERVISORES DE MANUTENÇÃO ELETROMECÂNICA", codigo: "9503"},
  {nome: "ELETRICISTAS-ELETRÔNICOS DE MANUTENÇÃO INDUSTRIAL", codigo: "9511"},
  {nome: "INSTALADORES E MANTENEDORES DE SISTEMAS DE ALARMES DE SEGURANÇA E DE INCÊNDIO", codigo: "9513"},
  {nome: "ELETRICISTAS-ELETRÔNICOS DE MANUTENÇÃO VEICULAR (AÉREA, TERRESTRE E NAVAL) ", codigo: "9531"},
  {nome: "MANTENEDORES DE ELEVADORES, ESCADAS E PORTAS AUTOMÁTICAS", codigo: "9541"},
  {nome: "REPARADORES DE APARELHOS ELETRODOMÉSTICOS", codigo: "9542"},
  {nome: "REPARADORES DE EQUIPAMENTOS DE ESCRITÓRIO", codigo: "9543"},
  {nome: "CONSERVADORES DE VIAS PERMANENTES (TRILHOS)", codigo: "9911"},
  {nome: "MANTENEDORES DE EQUIPAMENTOS DE LAZER ", codigo: "9912"},
  {nome: "MANTENEDORES DE CARROÇARIAS DE VEÍCULOS ", codigo: "9913"},
  {nome: "MANTENEDORES DE EDIFICAÇÕES", codigo: "9914"},
  {nome: "TRABALHADORES ELEMENTARES DE SERVIÇOS DE MANUTENÇÃO", codigo: "9921"},
  {nome: "TRABALHADORES ELEMENTARES DE CONSERVAÇÃO DE VIAS PERMANENTES ", codigo: "9922"},
  {nome: "MILITARES DA AERONÁUTICA", codigo: "0100"},
  {nome: "MILITARES DO EXÉRCITO", codigo: "0200"},
  {nome: "MILITARES DA MARINHA", codigo: "0300"},
  {nome: "CORONÉIS, TENENTES-CORONÉIS E MAJORES DA POLÍCIA MILITAR", codigo: "0401"},
  {nome: "CAPITÃES DA POLÍCIA MILITAR", codigo: "0402"},
  {nome: "TENENTES DA POLÍCIA MILITAR", codigo: "0403"},
  {nome: "PRAÇAS ESPECIAIS DA POLÍCIA MILITAR", codigo: "0411"},
  {nome: "SUBTENENTES E SARGENTOS DA POLÍCIA MILITAR", codigo: "0412"},
  {nome: "CABOS E SOLDADOS DA POLÍCIA MILITAR", codigo: "0413"},
  {nome: "CORONÉIS, TENENTES-CORONÉIS E MAJORES DE BOMBEIRO MILITAR", codigo: "0501"},
  {nome: "CAPITÃES DO CORPO DE BOMBEIROS", codigo: "0502"},
  {nome: "TENENTES DO CORPO DE BOMBEIROS", codigo: "0503"},
  {nome: "PRAÇAS ESPECIAIS DE BOMBEIRO", codigo: "0511"},
  {nome: "SUBTENENTES E SARGENTOS DO CORPO DE BOMBEIROS", codigo: "0512"},
  {nome: "CABOS E SOLDADOS DO CORPO DE BOMBEIROS", codigo: "0513"},
  {nome: "OCUPAÇÕES MAL ESPECIFICADAS", codigo: "0"}
])

Queixa.create!([
  {nome: "Fecha olhos sem força (mm)", categoria: "olhos", categoria_queixa_id: 1},
  {nome: "Fecha olhos com força (mm)", categoria: "olhos", categoria_queixa_id: 1},
  {nome: "Triquíase (S / N)", categoria: "olhos", categoria_queixa_id: 1},
  {nome: "Ectrópio ( S / N )", categoria: "olhos", categoria_queixa_id: 1},
  {nome: "Catarata ( S / N )", categoria: "olhos", categoria_queixa_id: 1},
  {nome: "Dimin. Sensibilidade da Córnea ( S / N )", categoria: "olhos", categoria_queixa_id: 1},
  {nome: "Opacidade Corneana Cetral", categoria: "olhos", categoria_queixa_id: 1},
  {nome: "Acuidade Visual", categoria: "olhos", categoria_queixa_id: 1},
  {nome: "Ressecamento", categoria: "nariz", categoria_queixa_id: 2},
  {nome: "Feridas", categoria: "nariz", categoria_queixa_id: 2},
  {nome: "Perfuração de Septo", categoria: "nariz", categoria_queixa_id: 2},
  {nome: "Nervo Radial", categoria: "membros_superiores", categoria_queixa_id: 3},
  {nome: "Nervo Ulnar", categoria: "membros_superiores", categoria_queixa_id: 3},
  {nome: "Nervo mediano", categoria: "membros_superiores", categoria_queixa_id: 3},
  {nome: "Abdução do 5° dedo", categoria: "membros_superiores", categoria_queixa_id: 3},
  {nome: "Abdução do polegar", categoria: "membros_superiores", categoria_queixa_id: 3},
  {nome: "Extensores do punho", categoria: "membros_superiores", categoria_queixa_id: 3},
  {nome: "Nervo Fibular", categoria: "membros_inferiores", categoria_queixa_id: 4},
  {nome: "Nervo Tibial Posterior", categoria: "membros_inferiores", categoria_queixa_id: 4},
  {nome: "Extensão Hálux", categoria: "membros_inferiores", categoria_queixa_id: 4},
  {nome: "Dorsiflexão do pé", categoria: "membros_inferiores", categoria_queixa_id: 4}
])

SinaisSintoma.create!([
  {nome: "Súbito e inesperado"},
  {nome: "Acompanhados de febre e mal estar"},
  {nome: "Aparecimento de novas lesões"},
  {nome: "Ulcerações de lesões"},
  {nome: "Envolvimento de muitos nervos"},
  {nome: "Boa resposta aos esteróides"},
  {nome: "Lento e insidioso"},
  {nome: "Sem febre e mal estar"},
  {nome: "Poucas lesões novas"},
  {nome: "Sem Ulceração"},
  {nome: "Nenhuma ou algum nervo envolvido"},
  {nome: "Resposta não pronunciada aos esteróides"}
])

User.create!([{nome: "Gabriel Lacerda dos Santos", cpf: "", email: "gabrielvash@gmail.com", cidade_id: 139, role: "administrador", password: '123456', password_confirmation: '123456', reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2018-06-04 11:39:02", last_sign_in_at: "2018-03-12 12:14:47", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1"}])

