class CreateDantFaixaEtaria < ActiveRecord::Migration[5.1]
  def change
    create_table :dant_faixa_etaria do |t|
      t.integer :hipertenso_m_1
      t.integer :hipertenso_m_1_4
      t.integer :hipertenso_m_5_9
      t.integer :hipertenso_m_10_14
      t.integer :hipertenso_m_15_19
      t.integer :hipertenso_m_20_29
      t.integer :hipertenso_m_30_39
      t.integer :hipertenso_m_40_49
      t.integer :hipertenso_m_50_59
      t.integer :hipertenso_m_60_69
      t.integer :hipertenso_m_70_79
      t.integer :hipertenso_m_80
      t.integer :hipertenso_f_1
      t.integer :hipertenso_f_1_4
      t.integer :hipertenso_f_5_9
      t.integer :hipertenso_f_10_14
      t.integer :hipertenso_f_15_19
      t.integer :hipertenso_f_20_29
      t.integer :hipertenso_f_30_39
      t.integer :hipertenso_f_40_49
      t.integer :hipertenso_f_50_59
      t.integer :hipertenso_f_60_69
      t.integer :hipertenso_f_70_79
      t.integer :hipertenso_f_80
      t.integer :diabetico_m_1
      t.integer :diabetico_m_1_4
      t.integer :diabetico_m_5_9
      t.integer :diabetico_m_10_14
      t.integer :diabetico_m_15_19
      t.integer :diabetico_m_20_29
      t.integer :diabetico_m_30_39
      t.integer :diabetico_m_40_49
      t.integer :diabetico_m_50_59
      t.integer :diabetico_m_60_69
      t.integer :diabetico_m_70_79
      t.integer :diabetico_m_90
      t.integer :diabetico_f_1
      t.integer :diabetico_f_1_4
      t.integer :diabetico_f_5_9
      t.integer :diabetico_f_10_14
      t.integer :diabetico_f_15_19
      t.integer :diabetico_f_20_29
      t.integer :diabetico_f_30_39
      t.integer :diabetico_f_40_49
      t.integer :diabetico_f_50_59
      t.integer :diabetico_f_60_69
      t.integer :diabetico_f_70_79
      t.integer :diabetico_f_80
      t.integer :diabetico_hipertenso_m_1
      t.integer :diabetico_hipertenso_m_1_4
      t.integer :diabetico_hipertenso_m_5_9
      t.integer :diabetico_hipertenso_m_10_14
      t.integer :diabetico_hipertenso_m_15_19
      t.integer :diabetico_hipertenso_m_20_29
      t.integer :diabetico_hipertenso_m_30_39
      t.integer :diabetico_hipertenso_m_40_49
      t.integer :diabetico_hipertenso_m_50_59
      t.integer :diabetico_hipertenso_m_60_69
      t.integer :diabetico_hipertenso_m_70_79
      t.integer :diabetico_hipertenso_m_80
      t.integer :diabetico_hipertenso_f_1
      t.integer :diabetico_hipertenso_f_1_4
      t.integer :diabetico_hipertenso_f_5_9
      t.integer :diabetico_hipertenso_f_10_14
      t.integer :diabetico_hipertenso_f_15_19
      t.integer :diabetico_hipertenso_f_20_29
      t.integer :diabetico_hipertenso_f_30_39
      t.integer :diabetico_hipertenso_f_40_49
      t.integer :diabetico_hipertenso_f_50_59
      t.integer :diabetico_hipertenso_f_60_69
      t.integer :diabetico_hipertenso_f_70_79
      t.integer :diabetico_hipertenso_f_80
      t.integer :obeso_m_1
      t.integer :obeso_m_1_4
      t.integer :obeso_m_5_9
      t.integer :obeso_m_10_14
      t.integer :obeso_m_15_19
      t.integer :obeso_m_20_29
      t.integer :obeso_m_30_39
      t.integer :obeso_m_40_49
      t.integer :obeso_m_50_59
      t.integer :obeso_m_60_69
      t.integer :obeso_m_70_79
      t.integer :obeso_m_80
      t.integer :obeso_f_1
      t.integer :obeso_f_1_4
      t.integer :obeso_f_5_9
      t.integer :obeso_f_10_14
      t.integer :obeso_f_15_19
      t.integer :obeso_f_20_29
      t.integer :obeso_f_30_39
      t.integer :obeso_f_40_49
      t.integer :obeso_f_50_59
      t.integer :obeso_f_60_69
      t.integer :obeso_f_70_79
      t.integer :obeso_f_80
      t.integer :tabagismo_m_1_8
      t.integer :tabagismo_m_9_11
      t.integer :tabagismo_m_12_17
      t.integer :tabagismo_m_18_24
      t.integer :tabagismo_m_25_34
      t.integer :tabagismo_m_35_44
      t.integer :tabagismo_m_45_54
      t.integer :tabagismo_m_55_64
      t.integer :tabagismo_m_65
      t.integer :tabagismo_f_1_8
      t.integer :tabagismo_f_9_11
      t.integer :tabagismo_f_12_17
      t.integer :tabagismo_f_18_24
      t.integer :tabagismo_f_25_34
      t.integer :tabagismo_f_35_44
      t.integer :tabagismo_f_45_54
      t.integer :tabagismo_f_55_64
      t.integer :tabagismo_f_65
      t.integer :etilismo_m_1_8
      t.integer :etilismo_m_9_11
      t.integer :etilismo_m_12_17
      t.integer :etilismo_m_18_24
      t.integer :etilismo_m_25_34
      t.integer :etilismo_m_35_44
      t.integer :etilismo_m_45_54
      t.integer :etilismo_m_55_64
      t.integer :etilismo_m_65
      t.integer :etilismo_f_1_8
      t.integer :etilismo_f_9_11
      t.integer :etilismo_f_12_17
      t.integer :etilismo_f_18_24
      t.integer :etilismo_f_25_34
      t.integer :etilismo_f_35_44
      t.integer :etilismo_f_45_54
      t.integer :etilismo_f_55_64
      t.integer :etilismo_f_65
      t.references :dant_request, foreign_key: true

      t.timestamps
    end
  end
end
